module.exports = {
  'array-bracket-spacing': [1, 'never'],
  'arrow-spacing': 1,
  'block-spacing': [1, 'never'],
  'brace-style': 1,
  'comma-spacing': [
    1,
    {
      before: false,
      after: true,
    },
  ],
  'comma-style': [1, 'last'],
  'computed-property-spacing': [1, 'never'],
  eqeqeq: 1,
  'func-call-spacing': [1, 'never'],
  'import/first': 1,
  'import/no-duplicates': 1,
  'import/no-unresolved': 2,
  'import/imports-first': 2,
  'import/newline-after-import': 1,
  'import/no-dynamic-require': 0,
  'import/no-extraneous-dependencies': 2,
  'import/no-named-as-default': 0,
  'import/no-webpack-loader-syntax': 0,
  'import/prefer-default-export': 0,
  indent: [
    1,
    2,
    {
      SwitchCase: 1,
    },
  ],
  'jsx-quotes': [1, 'prefer-double'],
  'key-spacing': [
    1,
    {
      beforeColon: false,
      afterColon: true,
    },
  ],
  'multiline-ternary': [0, 'never'],
  'new-cap': 1,
  'new-parens': 1,
  'no-alert': 1,
  'no-console': 1,
  'no-debugger': 0,
  'no-extend-native': 1,
  'no-extra-semi': 1,
  'no-inline-comments': 1,
  'no-lone-blocks': 1,
  'no-lonely-if': 1,
  'no-multi-spaces': 1,
  'no-multi-str': 1,
  'no-multiple-empty-lines': [
    1,
    {
      max: 2,
    },
  ],
  'no-negated-condition': 1,
  'no-self-compare': 1,
  'no-shadow': 1,
  'no-trailing-spaces': [
    1,
    {
      skipBlankLines: true,
    },
  ],
  'no-undef': 1,
  'no-undefined': 1,
  'no-underscore-dangle': 0,
  'no-unneeded-ternary': 1,
  'no-unreachable': 1,
  'no-unused-expressions': 1,
  'no-unused-vars': 1,
  'no-use-before-define': 1,
  'no-var': 1,
  'no-void': 1,
  'padding-line-between-statements': [
    1,
    { blankLine: 'always', prev: '*', next: 'return' },
    { blankLine: 'always', prev: ['const', 'let', 'var'], next: '*' },
    { blankLine: 'any', prev: ['const', 'let', 'var'], next: ['const', 'let', 'var'] },
  ],
  'react/jsx-uses-react': 1,
  'react/jsx-indent': [1, 2],
  'react/jsx-uses-vars': 1,
  'react/prop-types': 1,
  'react/jsx-handler-names': 0,
  'sort-vars': 1,
  'space-before-blocks': 1,
  'space-before-function-paren': [
    1,
    {
      anonymous: 'never',
      named: 'never',
      asyncArrow: 'always',
    },
  ],
  'space-in-parens': [1, 'never'],
  'space-infix-ops': 1,
  'react-hooks/rules-of-hooks': 'error',
  'react-hooks/exhaustive-deps': 0,
  'react/react-in-jsx-scope': 0,
};
